frequency: 20
sensor_timeout: 0.2
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
publish_tf: true
print_diagnostics: false
debug: false

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: /imu
imu0_config: [false, false, false, false, false,  true,
              false, false, false, false, false,  true,
               true, false, false]
imu0_nodelay: true
imu0_differential: false
imu0_relative: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

odom0: /odom
odom0_config: [false, false, false, false, false, false,
                true,  true, false, false, false, false,
               false, false, false]
odom0_nodelay: false
odom0_differential: false
odom0_relative: false
odom0_queue_size: 10

use_control: false
